### ISSUE TITLE
open pose using template

### ISSUE THREAD

**Issue by dinnercoding** [dhrim/cau_2022#3]
안녕하세요! cau 2022 수강 중인 학생입니다.
![image](https://user-images.githubusercontent.com/63527907/149727322-1e7da2c7-ffc9-4a95-89e1-413f36ca62b3.png)

해당하는 부분에 아래 코드가 추가되어야 할 것 같습니다.
```
from config_reader import config_reader
```

감사합니다 :)

**Comment by dhrim** [comment]
엄청 감사합니다. 반영했어요.
